FROM tensorflow/tensorflow

COPY Requirements.txt . 

RUN pip install -r Requirements.txt 

COPY final_code_assignment_2.py /app/final_code_assignment_2.py

CMD ["python3", "/app/final_code_assignment_2.py"]

