FROM tensorflow/tensorflow

COPY requirements.txt . 

RUN pip install -r requirements.txt 

COPY final_code_assignment_2.py /app/final_code_assignment_2.py

CMD ["python3", "/app/final_code_assignment_2.py"]

