FROM tensorflow/tensorflow

ADD requirements.txt .

RUN pip install -r requirements.txt

COPY final code assignment2.py /app/final code assignment 2.py

CMD ["python", "/app/final code assignment 2.py"]

